version: '{build}'

#branches:
#  only:
#    - master

environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
      PATH: C:\Program Files\Java\jdk1.8.0\bin;%PATH%
      TARGET: -Pjava8
    - JAVA_HOME: C:\Program Files\Java\jdk9
      PATH: C:\Program Files\Java\jdk9\bin;%PATH%
      TARGET: -Pjava9

build_script:
  - mvn clean test %TARGET%
