name: Build and test
on:
  workflow_dispatch: # because sometimes you just want to force a branch to have tests run
  pull_request:
    types: [ opened, synchronize, reopened ]
  push:
    branches:
      - master
    paths:
      - .github/workflows/build.yaml

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        java-version:
          - 11
          - 17
          - 20
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Disable shallow clones so Sonar can have all the data
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: zulu
      - name: Run Java Tests
        run: ./gradlew test
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew jacocoTestReport sonarqube --info
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.java-version == '17' }}
