name: coverity-scan
on:
  workflow_dispatch: # because sometimes you just want to force a branch to have tests run
  push:
    branches:
      - "**"
    paths:
      - .github/workflows/coverity.yaml
  schedule:
    - cron: '0 0 1 * *' # Monthly on the 1st at 00:00 UTC

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: zulu
      - name: Download Coverity Build Tool
        run: |
          wget -q https://scan.coverity.com/download/java/linux64 --post-data "token=${{ secrets.COVERITY_TOKEN }}&project=nickrobison/fasttuple" -O cov-analysis-linux64.tar.gz
          mkdir cov-analysis-linux64
          tar xzf cov-analysis-linux64.tar.gz --strip 1 -C cov-analysis-linux64
      - name: Build with cov-build
        run: |
          export PATH=`pwd`/cov-analysis-linux64/bin:$PATH
          cov-build --dir cov-int ./gradlew clean build
      - name: Submit the result to Coverity Scan
        run: |
          tar czvf fasttuple.tgz cov-int
          curl \
            --form token=${{ secrets.COVERITY_TOKEN }} \
            --form email=nick@nickrobison.com \
            --form file=@fasttuple.tgz \
            --form version=${{ env.GITHUB_REF }} \
            --form description="`git rev-parse --short HEAD`" \
            https://scan.coverity.com/builds?project=nickrobison%2Ffasttuple